### PR TITLE
Error ew faceerr 1

### PR DESCRIPTION
**Pull request by bimaAgs**
hi @deividAlfa When converting, an error like this always appears. What's wrong with me?

image

### CODE REVIEW

**Comment by deividAlfa** [comment]
Hello, I enabled issues tab in my fork.

I have no idea, maybe you're using too new Linux os?
I've had lots of issues since 2020, so my compiling VM is still in Ubuntu 20.

**Comment by AriZuu** [comment]
I'd say that there is something wrong with your font file. Haven't seen that error before.

**Comment by bimaAgs** [comment]
> Hello, I enabled issues tab in my fork.
> 
> I have no idea, maybe you're using too new Linux os? I've had lots of issues since 2020, so my compiling VM is still in Ubuntu 20.

i am using cygwin in windows & venture os on mac still same error "ew faceer 1"

**Comment by bimaAgs** [comment]
> I'd say that there is something wrong with your font file. Haven't seen that error before.

iam using default font from windows, does it need the location address the font or just call it arial.ttf?

iam find this error in ttf2ugui.c

image

**Comment by AriZuu** [comment]
--font argument wants a filename. If .ttf file is not in current directory, you must give full path to it.
I have never used windows font files, so I don't really know if they are compatible with library.

**Comment by AriZuu** [comment]
Look at freetype error codes here: https://freetype.org/freetype2/docs/reference/ft2-error_code_values.html

Error code 1 means "cannot open resource", ie. your arial.ttf is not found.

**Comment by deividAlfa** [comment]
Of course, the ttf file must be in the same folder, it won't magically take it from Windows.
Otherwise specify the full path, i.e.:
```
--font=/cygdrive/C/Windows/Fonts/Arial.ttf
```

But I would simply copy the ttf there for easiness,  in fact it's the only way I've used it.

**Comment by AriZuu** [comment]
So this is now all solved then ?

**Comment by bimaAgs** [comment]
> So this is now all solved then ?

yes, this was solved by adding ' ' sign between the fonts like 'Seven Segment.ttf' and finally the font was converted,

image

thank you for clarifying the problem I was facing 
*Note i am using cygwin in windows and the library can work well

**Comment by AriZuu** [comment]
Ok. I'm closing this now.

**Pull request closed without merging**
